version: "3.9"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sns,sqs
      - DEFAULT_REGION=us-east-1
    volumes:
      - ./init_sns.sh:/etc/localstack/init/ready.d/init_sns.sh
