name: Run code quality check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install app dependencies
        run: pip install -r requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort pylint
      
      - name: Check format
        run: black --check .

      - name: Check import order
        run: isort . --check --profile black

      - name: Run linter
        run: pylint .